import turtle
#turtle.bgcolor('black')
s = turtle.Screen()
s.bgcolor('black')
t = turtle.Turtle()
t.speed(0.9)
t.pencolor('red')
t.left(140)
t.forward(180)
t.circle(-90, 200)
t.setheading(60)
t.circle(-90, 200)
t.forward(180)
t.hideturtle()
s.mainloop()